### ISSUE TITLE
Missing cookie message after starting synchronisation in AntennaPod with gpodder

### ISSUE THREAD

**Issue by update-freak** [oxtyped/gpodder2go#45]
After synchronisation I recognised that the sync is failed in AntennaPod.
Then I checked the logs in Portainer I found this line:
`missing cookie, have you logged in yet: &errors.errorString{s:"http: named cookie not present"}`

I have attached my podcast subscriptions and also the log from portainer.
[antennapod-feeds-2024-12-15.opml.txt](https://github.com/user-attachments/files/18141275/antennapod-feeds-2024-12-15.opml.txt)
[gpodder2go_logs.txt](https://github.com/user-attachments/files/18141276/gpodder2go_logs.txt)

docker compose:
```
services:
  gpodder2go:
  image: quay.io/mhrivnak/gpodder2go-container:mhrivnak-fork
  container_name: gpodder2go
  ports:
    - 3005:3005
  environment:
    - NO_AUTH=false
    - VERIFIER_SECRET_KEY=""
  volumes:
    - /volume1/docker/gpodder2go:/data
  restart: unless-stopped
```

EDIT: Not sure if its an but in gpodder or linked to AntennaPod (therefore also createt a ticket here: https://github.com/AntennaPod/AntennaPod/issues/7561)
